# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_cpf.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(540, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(540, 200))
        MainWindow.setMaximumSize(QtCore.QSize(540, 200))
        MainWindow.setBaseSize(QtCore.QSize(500, 200))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGeraCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraCPF.setEnabled(True)
        self.btnGeraCPF.setGeometry(QtCore.QRect(9, 24, 150, 50))
        self.btnGeraCPF.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnGeraCPF.setFont(font)
        self.btnGeraCPF.setObjectName("btnGeraCPF")
        self.inputGeraCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGeraCPF.setGeometry(QtCore.QRect(165, 24, 361, 50))
        self.inputGeraCPF.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.inputGeraCPF.setFont(font)
        self.inputGeraCPF.setText("")
        self.inputGeraCPF.setAlignment(QtCore.Qt.AlignCenter)
        self.inputGeraCPF.setObjectName("inputGeraCPF")
        self.btnValidaCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCPF.setGeometry(QtCore.QRect(9, 95, 150, 50))
        self.btnValidaCPF.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnValidaCPF.setFont(font)
        self.btnValidaCPF.setObjectName("btnValidaCPF")
        self.inputValidaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCPF.setGeometry(QtCore.QRect(165, 95, 361, 50))
        self.inputValidaCPF.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.inputValidaCPF.setFont(font)
        self.inputValidaCPF.setText("")
        self.inputValidaCPF.setAlignment(QtCore.Qt.AlignCenter)
        self.inputValidaCPF.setObjectName("inputValidaCPF")
        self.labelRetorno = QtWidgets.QLabel(self.centralwidget)
        self.labelRetorno.setEnabled(True)
        self.labelRetorno.setGeometry(QtCore.QRect(450, 150, 77, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRetorno.sizePolicy().hasHeightForWidth())
        self.labelRetorno.setSizePolicy(sizePolicy)
        self.labelRetorno.setMaximumSize(QtCore.QSize(16777215, 15))
        self.labelRetorno.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setLineWidth(1)
        self.labelRetorno.setText("")
        self.labelRetorno.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRetorno.setIndent(-1)
        self.labelRetorno.setObjectName("labelRetorno")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gera ou Valida CPF"))
        self.btnGeraCPF.setText(_translate("MainWindow", "GERAR CPF"))
        self.btnValidaCPF.setText(_translate("MainWindow", "VALIDAR CPF"))
